### ISSUE TITLE
uos support will come

### ISSUE THREAD

**Issue by leochen-g** [wechaty/puppet-wechat4u#39]
#https://github.com/nodeWechat/wechat4u/pull/303

I have submitted a PR to wechat4u，If the merge is successful, this repository can also support uos login.

I believe this is good news

**Comment by hahahasnoopy** [comment]
thanks a lot for your contribution 😄

**Comment by huan** [comment]
Thank you very much for the great improvement; it will be super valuable for the Wechaty developers who want to run the lightest system for WeChat!

**Comment by leochen-g** [comment]
> Thank you very much for the great improvement; it will be super valuable for the Wechaty developers who want to run the lightest system for WeChat!

It's my pleasure.
