### ISSUE TITLE
大文件上传问题，超过0.5MB的文件无法上传

### ISSUE THREAD

**Issue by danni-cool** [wechaty/puppet-wechat4u#70]
貌似 wechat4u 作者很久没处理pr了，所以看看puppet-wechat4u是否要做一些改动

wechat4u 
https://github.com/nodeWechat/wechat4u/issues/331

目前业务项目处理的临时bugfix
https://github.com/danni-cool/docker-wechatbot-webhook/blob/main/patches/wechat4u%2B0.7.12.patch

PR: https://github.com/nodeWechat/wechat4u/pull/332

**Comment by leochen-g** [comment]
已更新最新版本，感谢PR
